### ISSUE TITLE
[package.json] move dependencies to devDependencies

### ISSUE THREAD

**Issue by Kiyozz** [alexeychikk/piano-trainer#1]
Hey,

I'm the creator of electron-esbuild.

There is something I didn't document in electron-esbuild. You should move your dependencies in devDependencies unless it is an external dependency (or you explicitly need it in the packaged node_modules folder).

Why ? Because all used dependencies in your renderer or main sources will be packaged in your final bundle (main.js or index.js for renderer). 

If you make them dependencies, they will be in two places. In your bundle and in the packaged node_modules and node_modules ones are not used (because all dependencies are in your bundle)

**Comment by alexeychikk** [comment]
@Kiyozz Thanks! Will do.
