### ISSUE TITLE
Why does it have such a terrible sound quality?

### ISSUE THREAD

**Issue by FiftyFour7250** [alexeychikk/piano-trainer#2]
I hear a noise when playing sound, it feels like someone recorded the sound of each key on a cheap mic, and then just cut them assigned to each key here.

**Comment by alexeychikk** [comment]
@FiftyFour7250 Try bringing down in-app volume and increasing your system volume.
Also, internally piano-trainer uses [soundfont-player](https://github.com/danigb/soundfont-player) to play a sound when a key is pressed, it does not synthesize it on the fly.

**Comment by alexeychikk** [comment]
@FiftyFour7250 If you want to listen to your actual keyboard you should connect it to your pc through audio line-in or mic inputs or something similar. This app is not intended for audio-recording. Internal player is mostly for cases when I need to generate sound for the user to guess, and as a fallback sound when pressing a key.
